name: goodjob_language
description: Goodjob-SDk is designed to meet the needs of international translation. It synchronizes
 the translation results to the application with a key configuration, so that developers no longer need to focus on the translation and writing of copywriting during the development process, and can put more energy into research and development
version: 1.0.3
homepage: https://github.com/goodjob-ai/goodjob-flutter.git

environment:
  sdk: ">=2.1.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  dio: ^3.0.9
  dio_http_cache: ^0.2.6
  sqflite: ^1.3.1
  path: ^1.6.4
  quiver: ^2.0.5
  crypto: ^2.1.3
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true