name: goodjob_language
description: Goodjob-SDK是为了满足国际化翻译，实现了一键配置翻译结果同步到应用上，使开发者在开发过程中不再需要关注于文案的翻译和撰写，能将更大的精力放在研发上。
version: 1.0.2
homepage: https://github.com/goodjob-ai/goodjob-flutter.git

environment:
  sdk: ">=2.1.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  dio: ^3.0.9
  dio_http_cache: ^0.2.6
  sqflite: ^1.3.1
  path: ^1.6.4
  quiver: ^2.0.5
  crypto: ^2.1.3
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true